import { writeFileSync } from "node:fs";
import {
  EXPIRING_SOON_WINDOW_DAYS,
  LICENSE_PLANS,
  type License,
  type LicensePlan,
  type LicenseStatus,
} from "../src/lib/licenses/types";

/**
 * Deterministic PRNG (mulberry32): names, plans, and seat counts are identical
 * on every run for a given seed. Dates are not, since they are anchored to the
 * day the script runs (see TODAY), which is what keeps status and renewal date
 * agreeing after a regeneration.
 */
function mulberry32(seed: number): () => number {
  let a = seed;
  return () => {
    a |= 0;
    a = (a + 0x6d2b79f5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

const random = mulberry32(20260811);

const pick = <T,>(items: readonly T[]): T =>
  items[Math.floor(random() * items.length)] as T;

const intBetween = (min: number, max: number): number =>
  min + Math.floor(random() * (max - min + 1));

const COMPANY_PREFIXES = [
  "Northwind", "Contoso", "Fabrikam", "Globex", "Initech", "Umbrella",
  "Soylent", "Vandelay", "Wonka", "Stark", "Wayne", "Cyberdyne",
  "Hooli", "Pied Piper", "Aperture", "BlueOrigin", "Tyrell", "Massive",
  "Bluth", "Prestige", "Sterling", "Dunder", "Vehement", "Gringotts",
  "Kruger", "Oceanic",
];
const COMPANY_SUFFIXES = [
  "Industries", "Group", "Labs", "Systems", "Holdings", "Partners",
  "Analytics", "Logistics", "Health", "Financial",
];

const NOTE_TEMPLATES = [
  "Renewal owner is on parental leave until Q3, escalate to the CS lead.",
  "Migrated from the legacy billing plan in the last cycle.",
  "Requested a mid-term seat expansion, pending procurement sign-off.",
  "Security review completed, SOC 2 report shared with their team.",
  "Historically slow to renew, start the conversation 60 days out.",
  "Downgraded from Enterprise after a reorganisation.",
  "Pilot team only, wider rollout under discussion.",
  "Invoices are settled by their parent company.",
  "Two failed payment attempts on the last invoice.",
  "Champion left the company, relationship needs rebuilding.",
];

/** Anchor for all generated dates, so status and renewal date agree (assumption A1). */
const TODAY = new Date();

function isoDateOffset(days: number): string {
  const date = new Date(
    Date.UTC(TODAY.getUTCFullYear(), TODAY.getUTCMonth(), TODAY.getUTCDate()),
  );
  date.setUTCDate(date.getUTCDate() + days);
  return date.toISOString().slice(0, 10);
}

/**
 * Renewal dates are derived from the status so the two never contradict.
 * Suspended accounts get any renewal date, since suspension is an admin
 * action independent of the date (assumption A1).
 */
function renewalOffsetFor(status: LicenseStatus): number {
  switch (status) {
    case "Active":
      return intBetween(EXPIRING_SOON_WINDOW_DAYS + 1, 365);
    case "Expiring Soon":
      return intBetween(1, EXPIRING_SOON_WINDOW_DAYS);
    case "Expired":
      return intBetween(-400, -1);
    case "Suspended":
      return intBetween(-180, 300);
  }
}

function seatsFor(plan: LicensePlan, index: number): { used: number; allowed: number } {
  const allowed =
    plan === "Trial" ? intBetween(3, 15)
    : plan === "Standard" ? intBetween(20, 120)
    : intBetween(150, 900);

  // Every 9th record is over-provisioned, e.g. after a downgrade (assumption A3).
  if (index % 9 === 0) {
    return { used: allowed + intBetween(1, 12), allowed };
  }
  return { used: intBetween(0, allowed), allowed };
}

const STATUS_WEIGHTS: LicenseStatus[] = [
  "Active", "Active", "Active", "Active", "Active",
  "Expiring Soon", "Expiring Soon", "Expiring Soon",
  "Expired", "Expired",
  "Suspended",
];

function generate(count: number): License[] {
  const usedNames = new Set<string>();
  const licenses: License[] = [];

  for (let index = 0; index < count; index += 1) {
    let customerName = "";
    do {
      customerName = `${pick(COMPANY_PREFIXES)} ${pick(COMPANY_SUFFIXES)}`;
    } while (usedNames.has(customerName));
    usedNames.add(customerName);

    const plan = pick(LICENSE_PLANS);
    const status = pick(STATUS_WEIGHTS);
    const { used, allowed } = seatsFor(plan, index);
    const slug = customerName.toLowerCase().replace(/[^a-z]+/g, "");

    licenses.push({
      id: `lic_${String(index + 1).padStart(3, "0")}`,
      customerName,
      plan,
      status,
      seatsUsed: used,
      seatsAllowed: allowed,
      renewalDate: isoDateOffset(renewalOffsetFor(status)),
      accountOwnerEmail: `${slug.slice(0, 14)}@example.com`,
      createdDate: isoDateOffset(-intBetween(400, 1600)),
      notes: pick(NOTE_TEMPLATES),
    });
  }

  return licenses;
}

const banner = `// Generated by scripts/generate-fixtures.ts. Do not edit by hand.
// Regenerate with: bun run generate:fixtures
`;

const body = `import type { License } from "./types";

export const LICENSE_FIXTURES: License[] = ${JSON.stringify(generate(50), null, 2)};
`;

writeFileSync("src/lib/licenses/fixtures.ts", `${banner}\n${body}`);
console.log("Wrote 50 fixtures to src/lib/licenses/fixtures.ts");
